package learning.android.kotlin.shared

enum class DataStroreType {
    PREMANENT_STORAGE_IN_SQL_LITE,
    PREMANENT_STORAGE_IN_PUBLIC_FILES,
    PREMANENT_STORAGE_IN_PRIVATE_FILES,
    TEMPORARY_STORAGE_IN_MUTABLE_LIST,
}